services:
  rvu_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rvu_api
    restart: unless-stopped
    env_file:
      - ${RVU_ENV_FILE:-.env}
    network_mode: host
